### ISSUE TITLE
Unicode Decode Error 

### ISSUE THREAD

**Issue by overfl0wd** [kootenpv/gittyleaks#12]
Hi again, I've found a few of my repositories to return the following error.

> Traceback (most recent call last):
  File "/home/dvnv/.local/lib/python3.6/site-packages/gittyleaks/gittyleaks.py", line 86, in get_git_matches
    revision, _tty_out=False))
  File "/home/dvnv/.local/lib/python3.6/site-packages/sh.py", line 884, in __str__
    return self.__unicode__()
  File "/home/dvnv/.local/lib/python3.6/site-packages/sh.py", line 893, in __unicode__
    self.call_args["decode_errors"])
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 6652274: invalid continuation byte

**Comment by dreaddesign** [comment]
old issue but still relevant for me.

I was able to find this error somewhat useful for debugging:
"UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 67580: invalid start byte"

i believe one of our developers using Windows committed to our repo with some software that interacts with github and used a windows specific character in the commit message ("smart quote" character)

unfortunately, if seems like the error happens at 

`return str(git('grep', '-i', '-e', '"({})"'.format(r'\|'.join(self.keywords)), revision, _tty_out=False))`

and it is outside of my skillset to figure out how to essentially take the result of the git grep and replace/ignore the improper characters.
