### ISSUE TITLE
It doesn't respond to a `SIGTERM`

### ISSUE THREAD

**Issue by wiseaidev** [kootenpv/gittyleaks#23]
It is not easy to stop the currently running process. It seems like a deadlock of some kind.

<details>

<summary><code>Full Output</code></summary>

```sh

(.venv) ➜ ✗ gittyleaks --find-anything
^Cencoding error at revision:  4456bceda305b1d011ed42cffa1cca807d0b81fc
^Cencoding error at revision:  2603d3f96a2eeeba032c8031ac8914a25c91e93a
^Cencoding error at revision:  021719042eba7ba74ce2f2f26bce0164d5e6d504
^Cencoding error at revision:  a3f34990b5eaaae19be8d456d534ad700ed7a88e
^Cencoding error at revision:  73d7da0b413d641eb4425ae558af7f0ef05999c3
^Cencoding error at revision:  13685d617c01d25f169e37b1034ebf3f472ab96d
^Cencoding error at revision:  4cee084f11a41963970ac6c54e49ee4d36ecfc9b
^Cencoding error at revision:  8757ec6953445dd3d1a663bf0e0cc6574a84d72c
^Cencoding error at revision:  1249d7b7c0504c87222d81446becc84a71fead11
^CException ignored in: <function _after_fork at 0x7f98b860cd30>
Traceback (most recent call last):
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 1538, in _after_fork
    thread._reset_internal_locks(False)
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 845, in _reset_internal_locks
    self._started._at_fork_reinit()
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 527, in _at_fork_reinit
    self._cond._at_fork_reinit()
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 253, in _at_fork_reinit
    self._lock._at_fork_reinit()
KeyboardInterrupt: 
encoding error at revision:  34875cc836734c5c89855d11b23208cee66b0e2a
^Cencoding error at revision:  96ff6505f65d82daf62cd61a913bcf963865fcc1
^Cencoding error at revision:  e75d9f2ce89d831910d207bb6acdc629f06f54ca
^Cencoding error at revision:  0259afd884046092ce7a4efe8b0abed2989d9a9f
^Cencoding error at revision:  d722f3107612a4b713d8ad360a3ca2d637964721
^Cencoding error at revision:  a38096873d8a6880587e3f4fc675b50d3f81724b
^CException ignored in: <function _releaseLock at 0x7f98b843ec10>
Traceback (most recent call last):
  File "~/.pyenv/versions/3.9.10/lib/python3.9/logging/__init__.py", line 227, in _releaseLock
    def _releaseLock():
KeyboardInterrupt: 
^Cencoding error at revision:  dd22a472a2638e501a34cbf6d618c0eb3b5e1da1
^Cencoding error at revision:  810b5904466896143315d68352cdc1add93fea1a
^Cencoding error at revision:  b28c5da6579f95e63a99bbdf1d0605b37d241921
^Cencoding error at revision:  88713f143f31c4db26589fb1160dd52c393c3e49
^Cencoding error at revision:  9202897e870d3a6d5d0f8f0f0ac43b1b64866abc
^Cencoding error at revision:  8586a00a1cd8af5a89f08c5b7c3979bb73b4c3f1
^Cencoding error at revision:  ec70be9e62e11f52284b90dd8a0ebe5146005171
encoding error at revision:  ec70be9e62e11f52284b90dd8a0ebe5146005171
^Cencoding error at revision:  8019f77da06b81edfc6884e906035f8366f82621
Exception ignored in: <function _releaseLock at 0x7f98b843ec10>
Traceback (most recent call last):
  File "~/.pyenv/versions/3.9.10/lib/python3.9/logging/__init__.py", line 227, in _releaseLock
^Cencoding error at revision:  4d42d2586b34249c1c25f162ec4661eab863d775
KeyboardInterrupt: 
Exception ignored in: <function _after_fork at 0x7f98b860cd30>
Traceback (most recent call last):
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 1525, in _after_fork
    threads.update(_dangling)
  File "~/.pyenv/versions/3.9.10/lib/python3.9/_weakrefset.py", line 66, in __iter__
    item = itemref()
KeyboardInterrupt: 
^Cencoding error at revision:  8019f77da06b81edfc6884e906035f8366f82621
encoding error at revision:  c2048f1b8d716b692fc2fcf0e5a14ac26e2e76b1
^Cencoding error at revision:  4d42d2586b34249c1c25f162ec4661eab863d775
Exception ignored in: <function _releaseLock at 0x7f98b843ec10>
Traceback (most recent call last):
  File "~/.pyenv/versions/3.9.10/lib/python3.9/logging/__init__.py", line 232, in _releaseLock
    _lock.release()
KeyboardInterrupt: 
Exception ignored in: <function _after_at_fork_child_reinit_locks at 0x7f98b843edc0>
Traceback (most recent call last):
  File "~/.pyenv/versions/3.9.10/lib/python3.9/logging/__init__.py", line 254, in _after_at_fork_child_reinit_locks
    for handler in _at_fork_reinit_lock_weakset:
  File "~/.pyenv/versions/3.9.10/lib/python3.9/_weakrefset.py", line 64, in __iter__
    with _IterationGuard(self):
encoding error at revision:  c2048f1b8d716b692fc2fcf0e5a14ac26e2e76b1
  File "~/.pyenv/versions/3.9.10/lib/python3.9/_weakrefset.py", line 24, in __enter__
    w._iterating.add(self)
KeyboardInterrupt: 
^CException ignored in sys.unraisablehook: <built-in function unraisablehook>
KeyboardInterrupt
encoding error at revision:  2d36855cfa4e5da4718c8f7ec5d4fb0d5bcb73a9
encoding error at revision:  2d36855cfa4e5da4718c8f7ec5d4fb0d5bcb73a9
encoding error at revision:  c2048f1b8d716b692fc2fcf0e5a14ac26e2e76b1
^Cgittyleaks user interupted
encoding error at revision:  fb6fcbe7c480d06162d1f17ba543c56f05d57934
^CException ignored in: <function _releaseLock at 0x7f98b843ec10>
Exception ignored in: <function _releaseLock at 0x7f98b843ec10>
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
KeyboardInterrupt
^Cencoding error at revision:  fb6fcbe7c480d06162d1f17ba543c56f05d57934
Exception ignored in: <function _after_fork at 0x7f98b860cd30>
Traceback (most recent call last):
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 1538, in _after_fork
    thread._reset_internal_locks(False)
Traceback (most recent call last):
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 845, in _reset_internal_locks
    self._started._at_fork_reinit()
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 527, in _at_fork_reinit
    self._cond._at_fork_reinit()
KeyboardInterrupt: 
KeyboardInterrupt: 
Traceback (most recent call last):
  File "~/.venv/bin/gittyleaks", line 33, in <module>
    sys.exit(load_entry_point('gittyleaks==0.0.31', 'console_scripts', 'gittyleaks')())
  File "~/.venv/lib/python3.9/site-packages/gittyleaks/gittyleaks.py", line 241, in main
    print('gittyleaks user interupted')
KeyboardInterrupt
^Cencoding error at revision:  8ce56bd124801dd5c46a4b6a1df9d6f65b3736e0
encoding error at revision:  8ce56bd124801dd5c46a4b6a1df9d6f65b3736e0
^Cencoding error at revision:  e2cd3a48f945d0d586fdc3ad232446fc40b1f41b
encoding error at revision:  e2cd3a48f945d0d586fdc3ad232446fc40b1f41b
^Cencoding error at revision:  54d2097ac011e04ce15410f64f8910dab38f8314
encoding error at revision:  54d2097ac011e04ce15410f64f8910dab38f8314
^Cencoding error at revision:  b963ab201cd3543506c4e309caf3433cf43a9727
encoding error at revision:  b963ab201cd3543506c4e309caf3433cf43a9727
^Cencoding error at revision:  240e5665a052ee46b46137798fa56f4571622c79
encoding error at revision:  240e5665a052ee46b46137798fa56f4571622c79
^Cencoding error at revision:  2d89615527f820b947924c9e4e554ac4f71acc87
encoding error at revision:  2d89615527f820b947924c9e4e554ac4f71acc87
Exception ignored in: <function _after_fork at 0x7f98b860cd30>
Traceback (most recent call last):
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 1525, in _after_fork
    threads.update(_dangling)
  File "~/.pyenv/versions/3.9.10/lib/python3.9/_weakrefset.py", line 64, in __iter__
    with _IterationGuard(self):
KeyboardInterrupt: 
^CException ignored in: <function _after_fork at 0x7f98b860cd30>
Traceback (most recent call last):
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 1539, in _after_fork
Exception ignored in: <function _releaseLock at 0x7f98b843ec10>
Exception ignored in: <function _releaseLock at 0x7f98b843ec10>
Traceback (most recent call last):
  File "~/.pyenv/versions/3.9.10/lib/python3.9/logging/__init__.py", line 227, in _releaseLock
    def _releaseLock():
Traceback (most recent call last):
^CKeyboardInterrupt: 
KeyboardInterrupt: 
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 1007, in _stop
    if not self.daemon:
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 1140, in daemon
    @property
KeyboardInterrupt: 
^Cencoding error at revision:  a74245b417392a5bbb0d9d206b336932c1ce6e51
encoding error at revision:  a74245b417392a5bbb0d9d206b336932c1ce6e51
^Cencoding error at revision:  01c15f4ade2169f1d0cfd9c18305253e9325ab7a
encoding error at revision:  01c15f4ade2169f1d0cfd9c18305253e9325ab7a
^Cencoding error at revision:  a32cc1540440a975631c19336dedfce2bc1a0ebd
Exception ignored in: <function _releaseLock at 0x7f98b843ec10>
Traceback (most recent call last):
  File "~/.pyenv/versions/3.9.10/lib/python3.9/logging/__init__.py", line 227, in _releaseLock
    def _releaseLock():
KeyboardInterrupt: 
^Cencoding error at revision:  a32cc1540440a975631c19336dedfce2bc1a0ebd
^CException ignored in: <function _releaseLock at 0x7f98b843ec10>
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
KeyboardInterrupt
Exception ignored in: <function _releaseLock at 0x7f98b843ec10>
^Cencoding error at revision:  d428d63294f12f6d2182359221f0cb5fe5c7292a
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
KeyboardInterrupt
^Cencoding error at revision:  d428d63294f12f6d2182359221f0cb5fe5c7292a
^CException ignored in: <function _releaseLock at 0x7f98b843ec10>
Traceback (most recent call last):
  File "~/.pyenv/versions/3.9.10/lib/python3.9/logging/__init__.py", line 227, in _releaseLock
    def _releaseLock():
KeyboardInterrupt: 
Exception ignored in: <function _after_fork at 0x7f98b860cd30>
Traceback (most recent call last):
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 1538, in _after_fork
    thread._reset_internal_locks(False)
KeyboardInterrupt: 
Exception ignored in: <function _releaseLock at 0x7f98b843ec10>
Traceback (most recent call last):
  File "~/.pyenv/versions/3.9.10/lib/python3.9/logging/__init__.py", line 227, in _releaseLock
    def _releaseLock():
KeyboardInterrupt: 
^Cencoding error at revision:  7201d18f389c2eb10a930b2dc3022fb98d84f2cc
encoding error at revision:  7201d18f389c2eb10a930b2dc3022fb98d84f2cc
^CException ignored in: <function _releaseLock at 0x7f98b843ec10>
^CException ignored in sys.unraisablehook: <built-in function unraisablehook>
KeyboardInterrupt
Exception ignored in: <function _releaseLock at 0x7f98b843ec10>
Traceback (most recent call last):
  File "~/.pyenv/versions/3.9.10/lib/python3.9/logging/__init__.py", line 227, in _releaseLock
    def _releaseLock():
KeyboardInterrupt: 
^Cencoding error at revision:  28c3dc84288b9b774f69482779c7591d34b1a7b4
encoding error at revision:  28c3dc84288b9b774f69482779c7591d34b1a7b4
^Cencoding error at revision:  9d16707bbb23a3043d8f41c16a80f65e4f5c9d59
encoding error at revision:  9d16707bbb23a3043d8f41c16a80f65e4f5c9d59
^Cencoding error at revision:  bcca07e144c39ef0d792ae468ebaa6be65ac3f77
encoding error at revision:  bcca07e144c39ef0d792ae468ebaa6be65ac3f77
Exception ignored in: <function _after_fork at 0x7f98b860cd30>
Traceback (most recent call last):
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 1538, in _after_fork
    thread._reset_internal_locks(False)
KeyboardInterrupt: 
^Cencoding error at revision:  31668c4777c80f8f94ce8734d674ba4a6a0c7172
encoding error at revision:  31668c4777c80f8f94ce8734d674ba4a6a0c7172
^Cencoding error at revision:  5efab0f27eaf290586dcfcf75bdeadc38ec5cf3d
Exception ignored in: <function _after_fork at 0x7f98b860cd30>
Traceback (most recent call last):
encoding error at revision:  5efab0f27eaf290586dcfcf75bdeadc38ec5cf3d
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 1525, in _after_fork
    threads.update(_dangling)
  File "~/.pyenv/versions/3.9.10/lib/python3.9/_weakrefset.py", line 65, in __iter__
    for itemref in self.data:
^CKeyboardInterrupt: 
encoding error at revision:  f13d78a6388fb4727f7ee7d11d4bd12674c67dc2
Exception ignored in: <function _after_fork at 0x7f98b860cd30>
Traceback (most recent call last):
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 1538, in _after_fork
    thread._reset_internal_locks(False)
Exception ignored in: <function _after_fork at 0x7f98b860cd30>
Traceback (most recent call last):
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 1538, in _after_fork
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 845, in _reset_internal_locks
    self._started._at_fork_reinit()
^C  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 527, in _at_fork_reinit
Exception ignored in: <function _releaseLock at 0x7f98b843ec10>
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
KeyboardInterrupt
    thread._reset_internal_locks(False)
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 857, in _reset_internal_locks
    self._tstate_lock = None
KeyboardInterrupt: 
    self._cond._at_fork_reinit()
KeyboardInterrupt: 
Exception ignored in: <function _releaseLock at 0x7f98b843ec10>
Traceback (most recent call last):
  File "~/.pyenv/versions/3.9.10/lib/python3.9/logging/__init__.py", line 231, in _releaseLock
    if _lock:
^CKeyboardInterrupt: 
Exception ignored in: <function _after_fork at 0x7f98b860cd30>
Traceback (most recent call last):
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 1538, in _after_fork
    thread._reset_internal_locks(False)
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 845, in _reset_internal_locks
encoding error at revision:  f13d78a6388fb4727f7ee7d11d4bd12674c67dc2
    self._started._at_fork_reinit()
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 527, in _at_fork_reinit
^C  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 253, in _at_fork_reinit
    self._lock._at_fork_reinit()
KeyboardInterrupt: 
encoding error at revision:  f526eb8484c65314accc48044e8e3fa03a60ae91
encoding error at revision:  f526eb8484c65314accc48044e8e3fa03a60ae91
^Cencoding error at revision:  b3961449b50328274392b17526933917e014f23e
Exception ignored in: <function _after_fork at 0x7f98b860cd30>
Traceback (most recent call last):
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 1538, in _after_fork
    thread._reset_internal_locks(False)
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 845, in _reset_internal_locks
    self._started._at_fork_reinit()
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 527, in _at_fork_reinit
Exception ignored in: <function _releaseLock at 0x7f98b843ec10>
    self._cond._at_fork_reinit()
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 253, in _at_fork_reinit
    self._lock._at_fork_reinit()
KeyboardInterrupt: 
^CException ignored in: <function _after_fork at 0x7f98b860cd30>
Traceback (most recent call last):
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 1539, in _after_fork
encoding error at revision:  5f83154520afe899e8a52bbae80f18091475a984
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
KeyboardInterrupt
^Cencoding error at revision:  b3961449b50328274392b17526933917e014f23e
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 1007, in _stop
    if not self.daemon:
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 1140, in daemon
    @property
KeyboardInterrupt: 
Exception ignored in: <function _releaseLock at 0x7f98b843ec10>
^CException ignored in: <function _releaseLock at 0x7f98b843ec10>
Traceback (most recent call last):
  File "~/.pyenv/versions/3.9.10/lib/python3.9/logging/__init__.py", line 231, in _releaseLock
    if _lock:
KeyboardInterrupt: 
Exception ignored in: <function _after_fork at 0x7f98b860cd30>
Traceback (most recent call last):
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 1538, in _after_fork
    thread._reset_internal_locks(False)
^C  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 856, in _reset_internal_locks
    self._is_stopped = True
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
KeyboardInterrupt
KeyboardInterrupt: 
encoding error at revision:  5f83154520afe899e8a52bbae80f18091475a984
^Cencoding error at revision:  3630f1143bf9399b5460c1a5f3803e06032474e0
encoding error at revision:  3630f1143bf9399b5460c1a5f3803e06032474e0
^CException ignored in: <function _releaseLock at 0x7f98b843ec10>
Traceback (most recent call last):
  File "~/.pyenv/versions/3.9.10/lib/python3.9/logging/__init__.py", line 227, in _releaseLock
encoding error at revision:  e1529992300ebac074be462feb3e34f3e5061dbf
    def _releaseLock():
KeyboardInterrupt: 
Exception ignored in: <function _after_fork at 0x7f98b860cd30>
Traceback (most recent call last):
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 1538, in _after_fork
    thread._reset_internal_locks(False)
^CException ignored in: <function _after_fork at 0x7f98b860cd30>
^CKeyboardInterrupt: 
encoding error at revision:  e1529992300ebac074be462feb3e34f3e5061dbf
gittyleaks user interupted
  File "~/.pyenv/versions/3.9.10/lib/python3.9/threading.py", line 857, in _reset_internal_locks
KeyboardInterrupt: 
Exception ignored in: <function _after_fork at 0x7f98b860cd30>
Exception ignored in sys.unraisablehook: <built-in function unraisablehook>
KeyboardInterrupt
encoding error at revision:  b4f93365de519e0ec123b4e0c620b9967b2e21ca
gittyleaks user interupted
^C^C^C^C^C^C^C^C^CTraceback (most recent call last):
Traceback (most recent call last):


^C^C^C^C^C
(.venv) ➜  
```

</details>

**Comment by kootenpv** [comment]
very weird tbh
