### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by chris-rudmin** [kootenpv/gittyleaks#8]
Just installed on windows10 x64.  Trying to execute the tool results in the following:
```
$ gittyleaks -h
Traceback (most recent call last):
  File "C:\Users\christopherr\AppData\Local\Programs\Python\Python37\Scripts\gittyleaks-script.py", line 11, in <module>
    load_entry_point('gittyleaks==0.0.23', 'console_scripts', 'gittyleaks')()
  File "c:\users\christopherr\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\christopherr\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 2693, in load_entry_point
    return ep.load()
  File "c:\users\christopherr\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 2324, in load
    return self.resolve()
  File "c:\users\christopherr\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 2330, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\christopherr\appdata\local\programs\python\python37\lib\site-packages\gittyleaks\gittyleaks.py", line 4, in <module>
    from sh import git
  File "c:\users\christopherr\appdata\local\programs\python\python37\lib\site-packages\sh.py", line 36, in <module>
    support." % __version__)
ImportError: sh 1.12.14 is currently only supported on linux and osx. please install pbs 0.110 (http://pypi.python.org/pypi/pbs) for windows support.
```

**Comment by chris-rudmin** [comment]
Explicitly installing pbs 0.110 does not resolve the error.

**Comment by tdashworth** [comment]
I am having a similar issue although a different package: 
```
Traceback (most recent call last):
  File "C:\Users\tashwort\AppData\Local\Programs\Python\Python38\Scripts\gittyleaks-script.py", line 11, in <module>
    load_entry_point('gittyleaks==0.0.31', 'console_scripts', 'gittyleaks')()
  File "c:\users\tashwort\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\tashwort\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "c:\users\tashwort\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 2462, in load
    return self.resolve()
  File "c:\users\tashwort\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\tashwort\appdata\local\programs\python\python38\lib\site-packages\gittyleaks\gittyleaks.py", line 4, in <module>
    from sh import git
  File "c:\users\tashwort\appdata\local\programs\python\python38\lib\site-packages\sh.py", line 40, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'
```

**Comment by Mode-77** [comment]
Looks like the same thing for me...

Any plans on supporting this for Windows?

```
Traceback (most recent call last):
  File "C:\Users\boden\AppData\Local\Programs\Python\Python310\Scripts\gittyleaks-script.py", line 33, in <module>
    sys.exit(load_entry_point('gittyleaks==0.0.31', 'console_scripts', 'gittyleaks')())
  File "C:\Users\boden\AppData\Local\Programs\Python\Python310\Scripts\gittyleaks-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\boden\AppData\Local\Programs\Python\Python310\lib\importlib\metadata\__init__.py", line 162, in load
    module = import_module(match.group('module'))
  File "C:\Users\boden\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\boden\AppData\Local\Programs\Python\Python310\lib\site-packages\gittyleaks\gittyleaks.py", line 4, in <module>
    from sh import git
  File "C:\Users\boden\AppData\Local\Programs\Python\Python310\lib\site-packages\sh.py", line 41, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'
```
